spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DB/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: DEBUG
